use openssl::rand::rand_bytes;

pub trait RandomGenerator {
    fn generate(&self, len: usize) -> Result<Vec<u8>, Box<dyn std::error::Error>>;
}

pub struct OpensslRandomGenerator;

impl RandomGenerator for OpensslRandomGenerator {
    fn generate(&self, len: usize) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        let mut buf = vec![0u8; len];
        rand_bytes(&mut buf)?;
        Ok(buf)
    }
}

/// One-shot helper to obtain cryptographically secure random bytes.
pub fn openssl_random_bytes(len: usize) -> Result<Vec<u8>, openssl::error::ErrorStack> {
    let mut buf = vec![0u8; len];
    rand_bytes(&mut buf)?;
    Ok(buf)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    struct MockRandomGenerator {
        called_with_len: AtomicUsize,
    }

    impl MockRandomGenerator {
        fn new() -> Self {
            Self {
                called_with_len: AtomicUsize::new(0),
            }
        }

        fn called_with(&self) -> usize {
            self.called_with_len
                .load(std::sync::atomic::Ordering::SeqCst)
        }
    }

    impl RandomGenerator for MockRandomGenerator {
        fn generate(&self, len: usize) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
            self.called_with_len.store(len, Ordering::SeqCst);
            Ok(vec![0xFF; len])
        }
    }

    #[test]
    fn test_openssl_generator_creates_correct_length() {
        let generator = OpensslRandomGenerator;
        let result = generator.generate(16).unwrap();
        assert_eq!(result.len(), 16);
    }

    #[test]
    fn test_openssl_generator_generates_different_values() {
        let generator = OpensslRandomGenerator;
        let first = generator.generate(16).unwrap();
        let second = generator.generate(16).unwrap();
        assert_ne!(first, second, "Generated bytes should be random");
    }

    #[test]
    fn test_mock_generator() {
        let generator = MockRandomGenerator::new();
        let result = generator.generate(32).unwrap();
        assert_eq!(result.len(), 32);
        assert_eq!(generator.called_with(), 32);
        assert!(result.iter().all(|&b| b == 0xFF));
    }

    #[test]
    fn test_zero_length_request() {
        let generator = OpensslRandomGenerator;
        let result = generator.generate(0).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_random_bytes_oneshot_basic() {
        let a = openssl_random_bytes(16).unwrap();
        let b = openssl_random_bytes(16).unwrap();
        assert_eq!(a.len(), 16);
        assert_eq!(b.len(), 16);
        assert_ne!(a, b);
    }
}
